In [2]:
#Import relevant librariess

import pandas as pd
import numpy as np
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time
import pymysql.cursors
from decouple import config 
from datetime import datetime
from dateutil.parser import parse
import pymysql
from sqlalchemy import create_engine, text
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import warnings
warnings.filterwarnings('ignore')
import os
from dotenv import load_dotenv
#from docx import Document
#from docx.shared import RGBColor
#from docx.enum.text import WD_COLOR_INDEX
import locale
locale.setlocale(locale.LC_ALL, 'fr_FR')

'fr_FR'

In [3]:
#Dates for the periods

#Dates for the most recent period
start_date = pd.to_datetime('2025-01-01')
today_date = datetime.today()
end_date = today_date
#Dates for the period before the most recent period
start_date_last = '2024-10-01'
end_date_last = '2024-12-31'

#Schooling year
year_schooling = ['2024-2025']

In [4]:
load_dotenv('id_cc.env')
email = os.getenv('EMAIL')
password_cc = os.getenv('PASSWORD')

True

In [ ]:
from oev_fonction import download_files
# Appel de la fonction
download_files()

'from oev_fonction import download_files\n# Appel de la fonction\ndownload_files() '

In [6]:
from oev_fonction import check_files
check_files([
    f'All_child_PatientCode_CaseID {today_date}.xlsx',
    f'Caris Health Agent - Enfant - APPELS OEV (created 2022-03-28) {today_date}.xlsx',
    f'forme_comptage_menage_en_utilisation {today_date}.xlsx',
    f'household_child  {today_date}.xlsx'
])

Checking for file: C:\Users\Moise\Downloads\Reports_MEAL\OEV\All_child_PatientCode_CaseID 2025-03-11 23:17:15.227233.xlsx
Checking for file: C:\Users\Moise\Downloads\Reports_MEAL\OEV\Caris Health Agent - Enfant - APPELS OEV (created 2022-03-28) 2025-03-11 23:17:15.227233.xlsx
Checking for file: C:\Users\Moise\Downloads\Reports_MEAL\OEV\forme_comptage_menage_en_utilisation 2025-03-11 23:17:15.227233.xlsx
Checking for file: C:\Users\Moise\Downloads\Reports_MEAL\OEV\household_child  2025-03-11 23:17:15.227233.xlsx
The following files are missing: ['All_child_PatientCode_CaseID 2025-03-11 23:17:15.227233.xlsx', 'Caris Health Agent - Enfant - APPELS OEV (created 2022-03-28) 2025-03-11 23:17:15.227233.xlsx', 'forme_comptage_menage_en_utilisation 2025-03-11 23:17:15.227233.xlsx', 'household_child  2025-03-11 23:17:15.227233.xlsx']

In [7]:
# Charger les variables d'environnement
load_dotenv('dot.env')
user = os.getenv('MYSQL_USER')
password = os.getenv('MYSQL_PASSWORD')
host = os.getenv('MYSQL_HOST')
db = os.getenv('MYSQL_DB')

True

In [8]:
# Download charges virales database from "Charges_virales_pediatriques.sql file"
from oev_fonction import execute_sql_query
env_path = 'dot.env'
sql_file_path = './Charges_virales_pediatriques.sql'

oev_data = execute_sql_query(env_path, sql_file_path)
display(oev_data.head(2))

,departement,commune,section,site,hospital_name,site,hospital_name,id_hospital,patient_code,id_patient,...,LTFU 30days,LTFU_1month_inf_6months,LTFU_6_inf12months,LTFU_12months_plus,is_positive_by_pcr,weight,weight_date,network,is_ugp,office
0,Nord-Est,Fort Liberte,1ère Dumas,CAP/HOFL,Hôpital de Fort Liberté,CAP/HOFL,Hôpital de Fort Liberté,21,CAP/HOFL/ST01218,16,...,No,No,No,No,No,56.6,2024-12-10,UGP,Yes,CAP
1,Nord,Cap Haitien,2ème Haut du Cap,CAP/HUJU,Hôpital Universitaire Justinien,CAP/HUJU,Hôpital Universitaire Justinien,22,CAP/HUJU/ST04431,17,...,Yes,No,No,Yes,No,34.5,2019-10-09,UGP,Yes,CAP

In [9]:
oev_data.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['departement', 'commune', 'section', 'site', 'hospital_name', 'site',
       'hospital_name', 'id_hospital', 'patient_code', 'id_patient',
       'carer_name', 'carer_address', 'carer_telephone', 'in_dots',
       'dots_facilitator', 'schooling_program', 'education_program',
       'gardening_program', 'gps', 'sex', 'date_of_birth', 'is_abandoned',
       'is_dead', 'first_name', 'last_name', 'in_club', 'club_type',
       'took_viral_load_test', 'viral_load_indetectable', 'viral_load_count',
       'prev_viral_load_count', 'last_viral_load_collection_date',
       'inh_initiation_date', 'inh_completion_date',
       'indetectable_ou_inf_1000', 'arv_start_date', 'regime',
       'all_arv_start_date', 'all_arv_end_date', 'actual_arv_regime',
       'prev_viral_load_date', 'viral_load_date', 'next_viral_load_date',
       'eligibility', 'last_session_date', 'is_actually_in_club', 'age',
       '9-12', '13-17', '18+', 'last_followup_date', 'next_appointment_date',
       'MMS', 'LTFU 6months', 'LTFU_1year', 'LTFU 30days',
       'LTFU_1month_inf_6months', 'LTFU_6_inf12months', 'LTFU_12months_plus',
       'is_positive_by_pcr', 'weight', 'weight_date', 'network', 'is_ugp',
       'office'],
      dtype='object')>

In [10]:
'date_of_birth' in oev_data.columns

True

In [11]:
oev_data.drop(oev_data.columns[3], axis=1, inplace=True)
display(oev_data.head(2))

,departement,commune,section,hospital_name,hospital_name,id_hospital,patient_code,id_patient,carer_name,carer_address,...,LTFU 30days,LTFU_1month_inf_6months,LTFU_6_inf12months,LTFU_12months_plus,is_positive_by_pcr,weight,weight_date,network,is_ugp,office
0,Nord-Est,Fort Liberte,1ère Dumas,Hôpital de Fort Liberté,Hôpital de Fort Liberté,21,CAP/HOFL/ST01218,16,,"Trou du Nord, Roche Plate, Zone Divilieu",...,No,No,No,No,No,56.6,2024-12-10,UGP,Yes,CAP
1,Nord,Cap Haitien,2ème Haut du Cap,Hôpital Universitaire Justinien,Hôpital Universitaire Justinien,22,CAP/HUJU/ST04431,17,Miss Swela,ORPHELINAT MOMBIN LATAYE EN FACE COMPAGNIE MAMBA,...,Yes,No,No,Yes,No,34.5,2019-10-09,UGP,Yes,CAP

In [12]:
# Charger les variables d'environnement
load_dotenv('dot.env')
user = os.getenv('MYSQL_USER')
password = os.getenv('MYSQL_PASSWORD')
host = os.getenv('MYSQL_HOST')
db = os.getenv('MYSQL_DB')

True

In [13]:
# This code snippet is attempting to download a charges virales database from a SQL file named "Charges_virales_pediatriques.sql". It sets the environment path to 'dot.env' and the SQL file path to './info_site.sql'. It then executes a SQL query using the provided environment path and SQL file path, and displays the first two rows of the query result using `infos.head(2)`.
env_path = 'dot.env'
sql_file_path = './info_site.sql'  # Update the file path to the correct location
infos = execute_sql_query(env_path, sql_file_path)
display(infos.head(2))

,Site,Hospital,Departement,Commune,network
0,PAP/CHAP,Centre Hospitalier d'Arcachon 32,Ouest,Carrefour,CMMB
1,PAP/CHOS,CHOSCAL- Centre Hospitalier Sainte-Catherine L...,Ouest,Cite Soleil,UGP

In [14]:
"""

def convert_columns_to_datetime(df, columns):
    for col in columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')
    return df

# Exemple d'utilisation
data = {
    'dob1': ['2020-01-01', 'not a date', '2021-05-12'],
    'dob2': ['2019/07/19', '2022-10-10', 'incorrect format'],
    'dob3': ['03-10-2023', '05-12-2021', '06-15-2018']
}

df = pd.DataFrame(data)

# Liste des colonnes à convertir
columns_to_convert = ['dob1', 'dob2', 'dob3']

# Appeler la fonction pour convertir les colonnes
df = convert_columns_to_datetime(df, columns_to_convert)

display(df)
"""

"\n\ndef convert_columns_to_datetime(df, columns):\n    for col in columns:\n        df[col] = pd.to_datetime(df[col], errors='coerce')\n    return df\n\n# Exemple d'utilisation\ndata = {\n    'dob1': ['2020-01-01', 'not a date', '2021-05-12'],\n    'dob2': ['2019/07/19', '2022-10-10', 'incorrect format'],\n    'dob3': ['03-10-2023', '05-12-2021', '06-15-2018']\n}\n\ndf = pd.DataFrame(data)\n\n# Liste des colonnes à convertir\ncolumns_to_convert = ['dob1', 'dob2', 'dob3']\n\n# Appeler la fonction pour convertir les colonnes\ndf = convert_columns_to_datetime(df, columns_to_convert)\n\ndisplay(df)\n"

In [15]:
#Creating the sites column to merge with the other oev_datasets
oev_data['Site'] = oev_data['patient_code'].apply(lambda x: x[0:8])
#converting dob column into datetime type
oev_data_on_hivhaiti = oev_data.merge(infos, on = 'Site', how = 'left')
#Creating age column
oev_data_on_hivhaiti['date_of_birth'].fillna('0000-00-00', inplace = True)

oev_data_on_hivhaiti['date_of_birth'] = pd.to_datetime(oev_data_on_hivhaiti['date_of_birth'], errors = 'coerce')

In [16]:
#new calls file
appel = pd.read_excel("C:\\Users\\Moise\\Downloads\\Reports_MEAL\\OEV\\Caris Health Agent - Enfant - APPELS OEV (created 2022-03-28) 2025-03-04.xlsx")
appel.rename(columns = {'form.appels_oev.date_appel': 'date_appel',
                       'form.appels_oev.parenttuteur_trouve': 'found',
                       'form.appels_oev.patient_code': 'patient_code'}, inplace = True)
appel['date_appel'] = pd.to_datetime(appel['date_appel'], errors = 'coerce')
appel['found'] = pd.to_numeric(appel['found'], errors = 'coerce')

appel_qi = appel[(appel['date_appel'] >= start_date_last) & (appel['date_appel'] <= end_date_last) &
                 (appel['found'] == 1)][['patient_code', 'date_appel', 'found']].drop_duplicates('patient_code')
appel_qj = appel[(appel['date_appel'] >= start_date) & (appel['date_appel'] <= end_date) & 
                 (appel['found']) == 1][['patient_code', 'date_appel', 'found']].drop_duplicates('patient_code')

#====================================================================================================
#create table alike services table
all_appel_served_q1q2 = appel_qi.merge(appel_qj[['patient_code', 'date_appel']], on = 'patient_code', how = 'left')

#====================================================================================================

print(f"Nombre d'appels Qi: {appel_qi.shape[0]}")
print(f"Nombre d'appels Qj: {appel_qj.shape[0]}")
print(f"Servis en Q1 et Q2: {all_appel_served_q1q2[all_appel_served_q1q2['date_appel_y'].notnull()].shape[0]}")

Nombre d'appels Qi: 518
Nombre d'appels Qj: 913
Servis en Q1 et Q2: 345

In [17]:
import pandas as pd

def process_calls(file_path, start_date_last, end_date_last, start_date, end_date):
    # Lire le fichier Excel
    appel = pd.read_excel(file_path)
    
    # Renommer les colonnes
    appel.rename(columns={'form.appels_oev.date_appel': 'date_appel',
                          'form.appels_oev.parenttuteur_trouve': 'found',
                          'form.appels_oev.patient_code': 'patient_code'}, inplace=True)
    
    # Convertir les colonnes en datetime et numérique
    appel['date_appel'] = pd.to_datetime(appel['date_appel'], errors='coerce')
    appel['found'] = pd.to_numeric(appel['found'], errors='coerce')
    
    # Filtrer les données pour les périodes spécifiées
    appel_qi = appel[(appel['date_appel'] >= start_date_last) & (appel['date_appel'] <= end_date_last) &
                     (appel['found'] == 1)][['patient_code', 'date_appel', 'found']].drop_duplicates('patient_code')
    appel_qj = appel[(appel['date_appel'] >= start_date) & (appel['date_appel'] <= end_date) &
                     (appel['found'] == 1)][['patient_code', 'date_appel', 'found']].drop_duplicates('patient_code')
    
    # Créer une table similaire à la table des services
    all_appel_served_q1q2 = appel_qi.merge(appel_qj[['patient_code', 'date_appel']], on='patient_code', how='left')
    
    # Calculer les résultats
    nombre_appel_qi = appel_qi.shape[0]
    nombre_appel_qj = appel_qj.shape[0]
    servis_q1_q2 = all_appel_served_q1q2[all_appel_served_q1q2['date_appel_y'].notnull()].shape[0]
    
    return nombre_appel_qi, nombre_appel_qj, servis_q1_q2

# Exemple d'utilisation
file_path = "C:\\Users\\Moise\\Downloads\\Reports_MEAL\\OEV\\Caris Health Agent - Enfant - APPELS OEV (created 2022-03-28) 2025-03-04.xlsx"


nombre_appel_qi, nombre_appel_qj, servis_q1_q2 = process_calls(file_path, start_date_last, end_date_last, start_date, end_date)

print(f"Nombre d'appels Qi: {nombre_appel_qi}")
print(f"Nombre d'appels Qj: {nombre_appel_qj}")
print(f"Servis en Q1 et Q2: {servis_q1_q2}")

Nombre d'appels Qi: 518
Nombre d'appels Qj: 913
Servis en Q1 et Q2: 345

In [18]:
import pandas as pd
from datetime import datetime
from dateutil.relativedelta import relativedelta
from dateutil.parser import parse

# Ensure necessary variables are defined

# Dates for the most recent period
start_date = pd.to_datetime('2025-01-01')
today_date = datetime.today()
end_date = today_date

# Dates for the period before the most recent period
start_date_last = pd.to_datetime('2024-10-01')
end_date_last = pd.to_datetime('2024-12-31')

# Creating the age column
def get_age(date):
    if pd.isnull(date):
        return None
    return relativedelta(end_date, parse(str(date))).years

# Convert 'date_of_birth' column to datetime, with errors='coerce' to handle invalid dates
oev_data_on_hivhaiti['date_of_birth'] = pd.to_datetime(oev_data_on_hivhaiti['date_of_birth'], errors='coerce')

# Map the 'get_age' function to the 'date_of_birth' column
oev_data_on_hivhaiti['ovc_age'] = oev_data_on_hivhaiti['date_of_birth'].map(get_age)


display(oev_data_on_hivhaiti[['date_of_birth','ovc_age']].head(2))

  date_of_birth  ovc_age
0    2009-12-29     15.0
1    2009-09-16     15.0

In [19]:
#OVC >= 18
data_sup18 = oev_data_on_hivhaiti[oev_data_on_hivhaiti['ovc_age'] >= 18]
#OVC < 18
data_inf18 = oev_data_on_hivhaiti[oev_data_on_hivhaiti['ovc_age'] < 18]

#All OVC data
ovc_data = pd.concat([data_inf18, data_sup18])

ovc_data.head(2)
ovc_data.shape[0]

,departement,commune,section,hospital_name,hospital_name,id_hospital,patient_code,id_patient,carer_name,carer_address,...,weight_date,network_x,is_ugp,office,Site,Hospital,Departement,Commune,network_y,ovc_age
0,Nord-Est,Fort Liberte,1ère Dumas,Hôpital de Fort Liberté,Hôpital de Fort Liberté,21,CAP/HOFL/ST01218,16,,"Trou du Nord, Roche Plate, Zone Divilieu",...,2024-12-10,UGP,Yes,CAP,CAP/HOFL,Hôpital de Fort Liberté,Nord-Est,Fort Liberte,UGP,15.0
1,Nord,Cap Haitien,2ème Haut du Cap,Hôpital Universitaire Justinien,Hôpital Universitaire Justinien,22,CAP/HUJU/ST04431,17,Miss Swela,ORPHELINAT MOMBIN LATAYE EN FACE COMPAGNIE MAMBA,...,2019-10-09,UGP,Yes,CAP,CAP/HUJU,Hôpital Universitaire Justinien,Nord,Cap Haitien,UGP,15.0

5991

In [20]:
def process_age_ranges(df, age_column, separation_age):

    # Convertir la colonne d'âge en numérique
    df[age_column] = pd.to_numeric(df[age_column], errors='coerce')

    # Fonction pour obtenir la tranche d'âge
    def age_range(age):
        if pd.isna(age):
            return None
        elif age in range(0, 1):
            return '< 1'
        elif age in range(1, 5):
            return '1 - 4'
        elif age in range(5, 10):
            return '5 - 9'
        elif age in range(10, 15):
            return '10 - 14'
        elif age in range(15, 18):
            return '15 - 17'
        elif age in range(18, 21):
            return '18 - 20'
        else:
            return '21+'

    # Ajouter une colonne 'age_range' au DataFrame
    df['age_range'] = df[age_column].map(age_range)

    # Filtrer les données en fonction des tranches d'âge
    df1 = df[df[age_column] < separation_age]
    df2 = df[(df[age_column] >= separation_age) & (df[age_column] <= 24)]

    # Afficher le nombre d'observations dans chaque groupe
    print(f"Ce dataset contient {df1.shape[0]} observations pour les tranches d'âge inférieures à {separation_age}.")

    print(f"Ce dataset contient {df2.shape[0]} observations pour les tranches d'âge compris entre {separation_age} et 24 ans.")
    # Afficher les résultats
    print(f"DataFrame pour les âges inférieurs à {separation_age}:")
    display(df1.head(2))
    print(f"DataFrame pour les âges compris entre {separation_age} et 24 ans:")
    display(df2.head(2))

    # Retourner les deux DataFrames
    return df1, df2

In [21]:
# Appeler la fonction
df1, df2 = process_age_ranges(ovc_data, 'ovc_age', 18)

Ce dataset contient 4041 observations pour les tranches d'âge inférieures à 18.
Ce dataset contient 1400 observations pour les tranches d'âge compris entre 18 et 24 ans.
DataFrame pour les âges inférieurs à 18:

,departement,commune,section,hospital_name,hospital_name,id_hospital,patient_code,id_patient,carer_name,carer_address,...,network_x,is_ugp,office,Site,Hospital,Departement,Commune,network_y,ovc_age,age_range
0,Nord-Est,Fort Liberte,1ère Dumas,Hôpital de Fort Liberté,Hôpital de Fort Liberté,21,CAP/HOFL/ST01218,16,,"Trou du Nord, Roche Plate, Zone Divilieu",...,UGP,Yes,CAP,CAP/HOFL,Hôpital de Fort Liberté,Nord-Est,Fort Liberte,UGP,15.0,15 - 17
1,Nord,Cap Haitien,2ème Haut du Cap,Hôpital Universitaire Justinien,Hôpital Universitaire Justinien,22,CAP/HUJU/ST04431,17,Miss Swela,ORPHELINAT MOMBIN LATAYE EN FACE COMPAGNIE MAMBA,...,UGP,Yes,CAP,CAP/HUJU,Hôpital Universitaire Justinien,Nord,Cap Haitien,UGP,15.0,15 - 17

DataFrame pour les âges compris entre 18 et 24 ans:

,departement,commune,section,hospital_name,hospital_name,id_hospital,patient_code,id_patient,carer_name,carer_address,...,network_x,is_ugp,office,Site,Hospital,Departement,Commune,network_y,ovc_age,age_range
162,Ouest,Cite Soleil,1ère Varreux,Maternité Isaie Jeanty,Maternité Isaie Jeanty,19,PAP/MIJC/ST01664,3280,,,...,MSPP,Yes,PAP,PAP/MIJC,Maternité Isaie Jeanty,Ouest,Cite Soleil,MSPP,22.0,21+
169,Ouest,Port-au-Prince,6ème Turgeau,Hôpital de l'Universite d'Etat d'Haiti,Hôpital de l'Universite d'Etat d'Haiti,17,PAP/HUEH/ST04060,3379,Locita Beaudry,cite soleil,...,UGP,Yes,PAP,PAP/HUEH,Hôpital de l'Universite d'Etat d'Haiti,Ouest,Port-au-Prince,UGP,23.0,21+

In [22]:
ovc_data.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['departement', 'commune', 'section', 'hospital_name', 'hospital_name',
       'id_hospital', 'patient_code', 'id_patient', 'carer_name',
       'carer_address', 'carer_telephone', 'in_dots', 'dots_facilitator',
       'schooling_program', 'education_program', 'gardening_program', 'gps',
       'sex', 'date_of_birth', 'is_abandoned', 'is_dead', 'first_name',
       'last_name', 'in_club', 'club_type', 'took_viral_load_test',
       'viral_load_indetectable', 'viral_load_count', 'prev_viral_load_count',
       'last_viral_load_collection_date', 'inh_initiation_date',
       'inh_completion_date', 'indetectable_ou_inf_1000', 'arv_start_date',
       'regime', 'all_arv_start_date', 'all_arv_end_date', 'actual_arv_regime',
       'prev_viral_load_date', 'viral_load_date', 'next_viral_load_date',
       'eligibility', 'last_session_date', 'is_actually_in_club', 'age',
       '9-12', '13-17', '18+', 'last_followup_date', 'next_appointment_date',
       'MMS', 'LTFU 6months', 'LTFU_1year', 'LTFU 30days',
       'LTFU_1month_inf_6months', 'LTFU_6_inf12months', 'LTFU_12months_plus',
       'is_positive_by_pcr', 'weight', 'weight_date', 'network_x', 'is_ugp',
       'office', 'Site', 'Hospital', 'Departement', 'Commune', 'network_y',
       'ovc_age', 'age_range'],
      dtype='object')>

In [32]:
def active_df(df):
    # Départements à exclure
    excluded_departments = ['Sud', "Grand'Anse", 'Nippes']

    # Filtrer les données selon les critères.  Handle potential missing values gracefully.
    df = df[
        (df['is_abandoned'] != 1) &
        (df['is_dead'] != 1) &
        (df['is_ugp'] == 'No') &
        (df['network_x'] != 'UGP') &
        (df['network_x']!= 'PIH') &
        (df['LTFU 30days'] =="No") &
        (~df['Departement'].isin(excluded_departments))  # Exclure les départements
    ]

    return df

In [35]:
'PIH' in ovc_data["network_x"]

False

In [29]:
file_active = active_df(ovc_data)
print(f'This dataset has {file_active.shape[0]} observation')
file_active.head(2)

This dataset has 1979 observation

,departement,commune,section,hospital_name,hospital_name,id_hospital,patient_code,id_patient,carer_name,carer_address,...,network_x,is_ugp,office,Site,Hospital,Departement,Commune,network_y,ovc_age,age_range
13,Ouest,Arcahaie,8ème Montrouis,POZ,POZ,44,MON/POZS/30311,286,unknow,0,...,FOSREF,No,PAP,MON/POZS,POZ,Ouest,Arcahaie,FOSREF,13.0,10 - 14
24,Nord,Pignon,1ère Savannette,Hôpital Bienfaisance de Pignon,Hôpital Bienfaisance de Pignon,25,PIG/HOBP/0000021,612,Therese Prevelouse,0,...,IMA,No,CAP,PIG/HOBP,Hôpital Bienfaisance de Pignon,Nord,Pignon,IMA,14.0,10 - 14

In [31]:
file_active.value_counts("network_x")

network_x
CMMB       1043
IMA         654
GHESKIO     132
BRIDGE       42
PIH          16
CDS          14
FOSREF       14
Santé         5
Name: count, dtype: int64

#### **1. CHARGES VIRALES PEDIATRIQUES**
***Note***: <span style='color:yellow'>Les cas d'abandon et de mort, le réseau UGP, ainsi que les sites inactifs PAP/CSAB & CAY/DSCC sont tous enlevés des calculs.</span>